### ISSUE TITLE
Voice Addition - TomTom Jane

### ISSUE THREAD

**Issue by fnuerpod** [pipeeeeees/waze-voicepack-links#10]
Just made a voice based off of the UK English Jane voice, which comes as a free voice on TomTom sat-nav units.

Wondering if you'd be interested in adding it to the community voices list. The quality is acceptable, however all distance measurements are in yards and miles - even on metric setting.

Link to pack is: https://waze.com/ul?acvp=6614e239-d4a1-409c-a1e9-348c960f1b32

**Comment by fnuerpod** [comment]
Forgot to mention, 1 mile is measured as 850 yards, which is the closest to a full mile in the Jane voice pack.

**Comment by pipeeeeees** [comment]
Added in the most recent commit. I also credited you and linked to this issue thread. Nice that you're able to make links too, if you want to chat about it sometime shoot me a message on discord (@ pipeeeeees)
