### ISSUE TITLE
Maxis Kids Safe mode

### ISSUE THREAD

**Issue by tohtonku** [pipeeeeees/waze-voicepack-links#12]
I have the original voice packs (voice by children in their cutesy voice). Can send it to you to create a link, please.

**Comment by pipeeeeees** [comment]
Sure thing, @tohtonku. Send a google drive link or equivalent - or DM me it on discord @pipeeeeees

**Comment by tohtonku** [comment]
https://www.dropbox.com/l/scl/AAD7mgXrErb00JdD7GGTaHCPx4DBfTsSu04


let me know if you can access the folder. and also when uploaded the link.
many thanks!

**Comment by pipeeeeees** [comment]
Requested access, check email

**Comment by tohtonku** [comment]
approved

**Comment by pipeeeeees** [comment]
Ah - as I suspected. If I'm not mistaken, this voice pack already exists under "Safe Mode Kids" on the readme, no?

**Comment by tohtonku** [comment]
This voice pack was released in 2015, in collaboration with Maxis (a
Malaysian telco company) with local kids talking in the Malaysian accent.

https://youtu.be/5PmvJKgetH4

I saw the Safe Kids mode ob github and actually added to my Waze but at the
moment unable to test it as I am on an island.

**Comment by tohtonku** [comment]
Looks like you are right. The safe mode is the same voicepack. Managed to
install it in my Waze. Way much clearer than mine (I recorded the voicepack
with a microphone hence the lower quality). Many thanks for your project!
