### ISSUE TITLE
Nandor, The Relentless

### ISSUE THREAD

**Issue by Ty-Ap** [pipeeeeees/waze-voicepack-links#14]
/ made with play.ht AI just for fun. Github hates mp3 so had to add media and convert. Love this project btw. not well versed in Python myself./

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/fbfbe80d-8e1c-4adf-84ed-cb5d25ea4623

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/cb84ea72-6cb3-44e1-b860-e8bc81b7f4ba

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/c595a3f5-fce1-4bf2-8db6-8a803fe86315

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/c33671ab-1342-488b-b73a-0f679314ead4

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/234a3216-63bb-4bc6-8860-6e80162ec1a6

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/e2978333-d499-4c40-a3c8-ffd36150a828

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/4e1a64b9-fd24-4810-8960-8a51bed8e96d

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/a2ece2cc-41fa-42e7-ae52-c1955bb04e8b

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/fbab00a1-9366-4467-ab7b-6d514add050d

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/1aa51d2d-aecb-476e-9bc5-14ffbac903bb

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/88fe6aa8-07bc-4718-ab4c-cf58190d5d34

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/f67069f0-d016-4273-b732-fe09129a8855

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/3643a113-4baa-489a-8e08-2ff42acadb41

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/b85cbc62-1a6a-497f-bb7c-03c66c4a033a

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/377e49b0-540e-4153-8af9-11c7da8aab86

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/4dd5d044-c1a1-4d57-860a-a0c92b16a742

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/590433d7-7b8f-424a-aeac-cc4493c120f9

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/54ed7826-3441-44e6-ac2b-176106bbf2f7

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/4f142129-4402-4687-9276-da6789445e88

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/116f7ca8-95b6-4879-ad72-ae44e36174ef

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/b54fd702-dbbc-4d8c-a6e9-9042c56eca6e

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/a34359da-7b28-4c6e-b13b-69f1a859d06a

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/1a361c4d-f068-4121-9efa-a433ed7fa189

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/cef85634-6c12-4755-9088-9b4fd2c20a2b

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/ca8219b1-2672-4578-bee4-c099f3ce4469

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/5fc669d5-9ab8-4a67-a6ef-0b592ba2b026

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/6e81ab38-1610-4356-b53b-f67362502cf6

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/86d2bb9d-bd73-409a-b258-f9e9fb4a157d

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/0045284c-5327-4820-bab9-a5f05818a013

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/a2d6fc05-aa02-43c7-9499-f6616c2b3223

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/2fa0f971-2bf0-46cf-98d7-8ce2559d10f2

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/aecd6884-d216-45cc-b03b-4bdf9d67bc2c

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/a7d0a085-5628-47b9-bbf0-008a1368cf60

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/d67ab5d6-6564-474b-acd6-6ada5bf6b1db

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/30e7fca7-ab80-430a-93ea-a1d444fab2e0

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/5e573edf-a80d-4eb4-b252-df04a30a3354

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/0d3a57ac-c31b-49a7-a5da-6add3b237115

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/cd5367b9-3d54-4ee4-8eec-2cb999233cf1

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/5f704b23-5c20-444d-b6b6-60ee4714cde3

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/451fb3e1-6214-47d1-bb12-ab5ec0bc60fb

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/adce3022-09c8-41d2-bbc7-0b0cc2407567

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/569ae2d8-a4c9-44ea-ba50-037eb67e767b

https://github.com/pipeeeeees/waze-voicepack-links/assets/118132556/bb893a3e-28e1-4c01-b565-aa2633cd2e0e

**Comment by pipeeeeees** [comment]
Hey, could you send me a onedrive/google drive/github repo link with all of these as mp3 files? I have some time tonight to make the pack before a busy week

**Comment by Ty-Ap** [comment]
For sure.

[GoogleDrive](https://drive.google.com/drive/folders/1WfXmB8RPhl5gvc06J6LoM3kiAeZakj2q?usp=drive_link)

**Comment by pipeeeeees** [comment]
https://waze.com/ul?acvp=5b890d52-2e02-4cec-ac37-75314224610d

Let me know if there are any issues with it!

**Comment by Ty-Ap** [comment]
Works flawlessly. Appreciate you !
