### ISSUE TITLE
Aircraft cabin chime - quiet notification sounds

### ISSUE THREAD

**Issue by hilsonp** [pipeeeeees/waze-voicepack-links#16]
Hello,

Can you check my suggestion at https://github.com/hilsonp/waze-voicepack-links/tree/main/conversion

The output directory contains files for a voice pack where the announcements would be simple, short and quite chime (same as in an aircraft cabin).
This would allow me to listen to podcast without muting completely waze (and loose the advantage of redirections or hazard warnings).

The beep_mapper.py reads the prompts_names.csv to copy beeps from the input directory into the correct output mp3.

Can you generate a "Aircarft cabin chimes" voice pack or let me know how I can proceed to do it ?
I would then test it and report back if anything needs adaptation.

Feedback is, for sure, welcome.

Thank you for the nice work !

Pierre

**Comment by pipeeeeees** [comment]
https://waze.com/ul?acvp=d9ada02c-50a3-4a2b-9178-43ad47d9906f

Try this, lmk if you want to make any changes. Just push your updated mp3 files to your fork and I can take care of the rest!

**Comment by hilsonp** [comment]
Thank you ! I did correct the roundabout sound that was assigned to
silence. Can you update the voice pack ?
I'll then try it for real tomorrow in the car ;-)

Le mar. 17 oct. 2023 à 00:17, David Pipes ***@***.***> a
écrit :

**Comment by pipeeeeees** [comment]
Ok I have swapped it out in the same voicepack. You will want to delete the pack off your phone and tap the link again. If it does not immediately update on your device, try a few more times. Lmk if you dont get the updated roundabout tone and I can make an entirely fresh link

**Comment by hilsonp** [comment]
Thank you. I'll try it a few days and report back to you.
My brother might do some custom sound, less saturated than those.

Le mar. 17 oct. 2023 à 00:59, David Pipes ***@***.***> a
écrit :

**Comment by hilsonp** [comment]
Hello !
I've been the the voice for a few hundred kilometers and this is fine for me. I'll keep it as is.
There is a bug in Waze where it keeps pausing the podcasts when playing a sound, whatever the option is set to which is very annoying as the main goal of this "voice" was to keep small notifications over uninterrupted media (Spotify is ok but Podcast will be stopped).
Any idea where to report bugs to waze ?
Thank you for your work.

**Comment by pipeeeeees** [comment]
Hey glad its working OK as is. I unfortunately do not know how to report bugs to waze, I've tried to find out before and failed.
