### ISSUE TITLE
KITT (Knight Rider)

### ISSUE THREAD

**Issue by Tommyvert** [pipeeeeees/waze-voicepack-links#19]
Hey, you been doing great work. I have some decent sound bites (AI generated) that I would like converted.
[VOICE.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/13467537/VOICE.zip)

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=a70efa64-ae58-40f3-837e-304411d25756

**Comment by pipeeeeees** [comment]
it may be too loud, I can quiet it down if desired

**Comment by Tommyvert** [comment]
It's good work, if you can quit it down it would be appreciated.

________________________________

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=f3e347b0-86ed-41f6-9d6f-79f30f73ebbb
