### ISSUE TITLE
Emilia Clarke German Voice Pack

### ISSUE THREAD

**Issue by sebseb1101** [pipeeeeees/waze-voicepack-links#20]
Thank you for all the work you do to give users a new experience with waze.

I used ElevenLabs to create the mp3s with Emilia Clarke's German dubbing actress, and I would really appreciate if you'd like to convert these into a shareable Waze link.

I have attached a zip with all the files (I hope it works, I havent used Github very often)
[Waze Emilia Clarke German.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/13571284/Waze.Emilia.Clarke.German.zip)

If there is any file missing I can create it if needed.

Thank you in advance!

**Comment by sebseb1101** [comment]
Is there any other way to leave a small tip than with Venemo?

**Comment by pipeeeeees** [comment]
Hey, check it out here: https://waze.com/ul?acvp=69a5fc6e-2dba-409a-8368-032448aa9c80

Let me know if this is satisfactory. No mile indicators were provided, but that is your preference. If you want me to add in miles, just include them in a reply and I can recreate it. 

No other options for tips at this time, but I appreciate your interest in tipping! As long as this pack provides you joy while driving, then I am satisfied enough
