### ISSUE TITLE
B1 battle droid voice pack

### ISSUE THREAD

**Issue by TMW-29** [pipeeeeees/waze-voicepack-links#21]
[B1 Final.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/13709823/B1.Final.zip)

**Comment by pipeeeeees** [comment]
Hey! Please rename the files per: https://github.com/pipeeeeees/waze-voicepack-links#have-mp3-files

This saves me some time. I've got a lot of packs to convert so it helps when they are all named to play nicely with the scripts

**Comment by TMW-29** [comment]
[B1 Renamed.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/13715715/B1.Renamed.zip)

Hey! Sorry for the late reply, here are the files renamed hope this works (I don't have voice recordings for miles I hope that doesn't matter, I did include the meters of course)

**Comment by pipeeeeees** [comment]
https://waze.com/ul?acvp=bdf8f53f-22ad-4595-a1f8-8194f0e099ff

Here it is, let me know if you'd like to make any changes

**Comment by TMW-29** [comment]
Hey it is almost perfect I realized I messed up one file export so the tickerpoints audio has to be replaced all the other files are perfect

All the files with the correct tickerpoints

[B1 Renamed.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/13717404/B1.Renamed.zip)

Only the correct tickerpoint audio file

[TickerPoints.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/13717403/TickerPoints.zip)

I am not sure if you need the whole pack again or just the replace audio file so I am just sending both just in case
Thank you so much already!

**Comment by pipeeeeees** [comment]
Hey! Sorry for the late response. Upgraded my rig to windows 11 and had to redo my setup. Try this: https://waze.com/ul?acvp=90e49160-f6f1-4a74-8978-ea790600eb48

**Comment by TMW-29** [comment]
Thank you so much for your time! It is perfect now. I really appreciate it!! Thank you so much
