### ISSUE TITLE
Austin Powers voice 

### ISSUE THREAD

**Issue by chrisjudevine** [pipeeeeees/waze-voicepack-links#25]
I did this with the old TomTom voice files and clips from the movies. I couldn't find some of the necessary audio so the seventh exit, and the one mile one sound terrible. The rest sound great. The info on your site have been so helpful. 

https://waze.com/ul?acvp=63828e08-6255-43f8-94ca-8347b7aa6c4d

**Comment by pipeeeeees** [comment]
Added to the readme - glad this repo served as a useful resource! 

If you'd like to add any voicepacks in future, feel free to fork, commit your changes, and pull request! Or open another issue either works :-)
