### ISSUE TITLE
Pamela Paz - Spanish voice pack for LatAm

### ISSUE THREAD

**Issue by rojodelmal** [pipeeeeees/waze-voicepack-links#26]
[spanish_latam_pamela_paz.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/14087066/spanish_latam_pamela_paz.zip)

Would appreciate if you can make a voice pack out of these files.

**Comment by pipeeeeees** [comment]
try this: https://waze.com/ul?acvp=16a785e7-6944-4a11-bb2b-4f98de329ce1

I guess this was an official waze voice given the extra files that came along with it?

**Comment by rojodelmal** [comment]
Thanks! Yeah, one of those deals between Waze and a big mobile carrier in the region.
