### ISSUE TITLE
Melina from Elden Ring (AI-Generated)

### ISSUE THREAD

**Issue by UnderscorePan** [pipeeeeees/waze-voicepack-links#27]
Hi there, would be so great if you can make a voice pack with this
[Melina Voicepack.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/14422230/Melina.Voicepack.zip)
Spent a lot of time on this, please contact me @notapan on discord if there's anything I missed out!

**Comment by UnderscorePan** [comment]
[Melina Voicepack V2.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/14423699/Melina.Voicepack.V2.zip)
With support for miles and rerouting

**Comment by pipeeeeees** [comment]
try this: https://waze.com/ul?acvp=34ae1b2d-3607-47d8-93b6-b979a51ccb2a

**Comment by MoisteryMachine** [comment]
Just a heads up, shes misspelled as Elder not Elden
