### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by O513** [pipeeeeees/waze-voicepack-links#30]
I have a bunch of mp3 I made. What do I do with them in order to create the voicepack in the right order? Furthermore, how do I even upload this into my iphones waze app? Im confused on where to start with this.

**Comment by pipeeeeees** [comment]
It's not an easy process, but I've sort of perfected / made an easy enough workflow for myself to do these creations and uploads. Most people have been sending me the mp3 files and I create the shareable link. In future, it is my intention to share a youtube video on how to make your own using the scripts provided in this repo and an android emulation. Just have not had time to yet

If you would like to have a shareable link generated, go ahead and share the mp3 files and follow the directions laid out in the readme.md of this repo to make formatting easy for me

**Comment by pipeeeeees** [comment]
See https://github.com/pipeeeeees/waze-voicepack-links/discussions/31
