### ISSUE TITLE
Learn how to do this

### ISSUE THREAD

**Issue by OptimusE1** [pipeeeeees/waze-voicepack-links#43]
Hey,
I found this really cool and was hoping you would be able to teach me how to do this. If not that’s possible it’s ok, but I have a bunch of streamers I plan on asking to do this. If I could do it myself that would be great if not then that’s ok I will just put them in here.

**Comment by pipeeeeees** [comment]
See https://github.com/pipeeeeees/waze-voicepack-links/discussions/31
