### ISSUE TITLE
Default voice - Android

### ISSUE THREAD

**Issue by Rimcrae0513** [pipeeeeees/waze-voicepack-links#44]
On the new Android version 14, after selecting a voice pack link and side loading it, the actual voice won't play. It is set to the default Waze voice and doesn't change. On Android 13, a fix was in place where if you change the default voice and then close the app it will work, but that solution no longer works.

**Comment by pipeeeeees** [comment]
Thank you for mentioning - I am aware of this issue in Android. However, I nor this repository are set up to fix this issue. This is an issue with Waze itself. The voicepacks still work just fine on iOS and the files themselves are still accessible from Waze's fileserver. Unfortunately it's something Waze's developers will need to fix

I am going to close this issue, but feel free to start a discussion post instead! r/waze has mentioned this bug every month for well over a year now it feels like
