### ISSUE TITLE
Software Automatic Mouth (Commodore 64)

### ISSUE THREAD

**Issue by CasketPizza** [pipeeeeees/waze-voicepack-links#45]
[Software Automatic Mouth for Waze.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/15167379/Software.Automatic.Mouth.for.Waze.zip)
The old SAM voice used in 80's videogames, as well as some modern ones for an eerie effect.

**Comment by pipeeeeees** [comment]
Sorry for the wait! Life has been busy lately. Here it is: https://waze.com/ul?acvp=61f4790a-ce45-439a-8642-d908385bb33d

**Comment by CasketPizza** [comment]
All good, greatly appreciated!  💜
