### ISSUE TITLE
Stormtrooper voice by Tarrachal

### ISSUE THREAD

**Issue by Tarrachal** [pipeeeeees/waze-voicepack-links#48]
I made most of it myself. Could be better, I think, but hopefully it'll do.
[Waze Stormtrooper.zip](https://github.com/user-attachments/files/15517081/Waze.Stormtrooper.zip)
They should all be under six seconds.

**Comment by pipeeeeees** [comment]
Hey! Here it is: https://waze.com/ul?acvp=dc3501e0-c57b-4409-97f4-5dded539e190

BTW: No need to be under six seconds with this mp3 upload method, just longer clips tend to be larger in file size and thus need some compressing to fit (so audio quality suffers some). Your pack ended up uploading at ~60k bitrate and 0.75MB in total filesize - pretty good. 

Feel free to reopen this issue if you want to change anything.

**Comment by Tarrachal** [comment]
Dude, you rock. You got a place I can drop a few bucks donation for your
efforts?

**Comment by pipeeeeees** [comment]
Thanks, I appreciate it! - venmo @pipeeeeees
