### ISSUE TITLE
James McCaffrey's Max Payne (AI generated)

### ISSUE THREAD

**Issue by toomanynights** [pipeeeeees/waze-voicepack-links#49]
Hello there!

It's been years since I came up with the idea of having Max Payne as a GPS guide, but only recently I learned that there is in fact Waze that allows you to create your own guides (to some extent). Spent quite a while teaching 11Labs his voice, writing the lines, recording and re-recording them dozens of times each, only to learn it involves a rooted device which I don't have. Bummer. 😒

So I was really glad to learn about your repo and the work you volunteer to do. Doing God's work, sir, thanks a lot.

I'm calling this one "Max Payne Express". Please mention "Rest in peace, James McCaffrey" in the description. Thanks again.

[max_payne_express.zip](https://github.com/user-attachments/files/15760385/max_payne_express.zip)

**Comment by pipeeeeees** [comment]
Hey, here it is: https://waze.com/ul?acvp=57314350-40b8-45f0-8be0-8807b5e8a312

Not sure if you intended on a lot of those lines to have "cut" starting and ending the line, but I am unfamiliar with Max Payne

Also, there were a lot of extra files in the folder, the only filenames I can semi-automate this process with are these: https://github.com/pipeeeeees/waze-voicepack-links/blob/main/conversion/mp3_filenames.txt ; I won't select between, for example, `Police.mp3`, `Police_2.mp3`, `Police_3.mp3` for one police voice line, that is up to you. My script just selects the non-enumerated filenames, so if you wanted one of the others resend it under the unenumerated filename found in the linked txt file and I can do it again!

**Comment by toomanynights** [comment]
Oh my. I'm so sorry 😰 I completely forgot that I stopped before I removed "cuts". Would you be able to re-upload once I fix it?

**Comment by pipeeeeees** [comment]
Sure thing, no worries - send them over when you have them ready!

**Comment by toomanynights** [comment]
@pipeeeeees , one question: back when I was generating those lines, I didn't know about "200" and so on (I read in your readme that those are for miles). Are those mandatory? Or it can be km-focused only? Just that I don't have 11labs account any more so I can't easily generate those.

**Comment by pipeeeeees** [comment]
@toomanynights they are not mandatory, I commented that as usually people will forget and many voice packs out there in the world become only partials / unusable by those who use the other metric. What some people do is they use 800meters for the half mile (`800.mp3`), 400meters for the quarter (`400.mp3`) so at least the voice pack says something for those users rather than defaulting to the default voice

**Comment by pipeeeeees** [comment]
up to you, but I would suggest in your case to just make a copy of 200 meters and rename it for 200.mp3 (same with 400, 800, and 1500) and that should be best

**Comment by toomanynights** [comment]
Ah, yes, makes perfect sense.

Here it is, double checked and ready:
https://drive.google.com/drive/folders/1mMdNDi1azGnUs3Pz6m1QL9SzT5l4s_XI?usp=sharing
I noticed there's one file that's not on your list: **rerouting**. It was in a manual I used when preparing the files.

**Comment by pipeeeeees** [comment]
Sorry its been a while!

Try this: https://waze.com/ul?acvp=5fc719b8-b40e-4cec-b5fc-1a5656428adb

**Comment by toomanynights** [comment]
Thank you very much, @pipeeeeees! I think it works.

FYI. You remember that workaround, where choosing the default voice would fix it if it didn't work? Looks like they "fixed" it in the latest version. By that I don't mean they fixed the problem, of course - they "fixed" the workaround, so it no longer works, rendering custom voices unusable on the latest version.

The only way around it I found is to downgrade Waze version.

Source: https://www.reddit.com/r/waze/s/CIG8OEJg7E

**Comment by pipeeeeees** [comment]
That's not good. It amazes me how slow Waze has moved to fix this. Introducing new bugs is a cherry on top. Lol
