### ISSUE TITLE
Minions voices available

### ISSUE THREAD

**Issue by humor4fun** [pipeeeeees/waze-voicepack-links#50]
I read a post that there are 2 new voice packs available now to go along with Despicable Me 4.

**Comment by pipeeeeees** [comment]
Nice - thanks for letting me know! I dont have mp3 files to make a pack for those unfortunately. I may get a shareable link up on the readme at some point

**Comment by Vaikiry** [comment]
> e

Many thanks

**Comment by Vaikiry** [comment]
> [minions.zip](https://github.com/user-attachments/files/22066687/minions.zip)
> 
> I got the minions mp3 files saved as he voice will be removed from Waze soon. Unfortunatelly I don't have time to create the shareable link currently, hence I upload it here if someone else has time to do it.

Many thanks!

**Comment by david83es** [comment]
@Vaikiry hero! My family was missing this voice badly! Thanks
