### ISSUE TITLE
bare minimum

### ISSUE THREAD

**Issue by chekyassine** [pipeeeeees/waze-voicepack-links#51]
Hello, 
I need a bare minimum voice pack containing crash, police and radar sounds. 
[Downloads.zip](https://github.com/user-attachments/files/16054822/Downloads.zip)
Thank you

**Comment by pipeeeeees** [comment]
Hi - sorry for the delay. Caught me right before vacation

So there are a few assumptions that had to be made. You offered a camera mp3 file but did not specify if this was red light camera or speed camera. I just used that file for both. Also, if there is no recording for the other spoken voice lines, the app defaults them to the default voice... so I had to record blank audio for all of the other voice lines. This may still disturb music or podcast playback, but that was the only way to avoid the app defaulting the other lines to the default voice. It may be possible to make a VERY short mp3 file with no audio to where the interruption is virtually nothing, but I don't have the time to look into that. If you can provide a very very short mp3 file of nothing I can remake the pack with it and you can test it out. If you do, please format the filenames according to: https://github.com/pipeeeeees/waze-voicepack-links/blob/main/conversion/mp3_filenames.txt - I went ahead and renamed the filenames you provided as it was just 3 files, but if you provide more in future please name them accoridng to that document. The readme.md has more information on filenaming too

https://waze.com/ul?acvp=8d194747-c45f-44e0-b034-01c89ee0e9af

let me know if this pack is ok or if you'd like to try something else. i think a minimal pack without interruptions may not be 100% perfect

**Comment by chekyassine** [comment]
Thank you so much. I actually disable all unneeded alerts from settings keeping only those 3. But if anyone need any modification, I'll be glad to do it. Thanks again!
