### ISSUE TITLE
VOX

### ISSUE THREAD

**Issue by JalanTuaKong** [pipeeeeees/waze-voicepack-links#53]
Hi guys. If anyone can make a voicepack out of this, it'd be greatly appreciated 😊
Did this as I was feeling nostalgic and since there was a GLADOS voicepack, I thought a VOX pack would've been nice too

https://www.dropbox.com/scl/fo/4zds33qnmxlzr4gfnunm8/AA9Aarre0z-9iIQVQuMlHFs?rlkey=fad6r7yam2oqv9ze6h56sbbdk&dl=0

**Comment by JalanTuaKong** [comment]
Actually, after  a few hours of editing  and trial and error on exporting to  reduce filesize and getting the emulator up, I got it working! Here's the link for everyone to enjoy 🙂

https://waze.com/ul?acvp=99e44cd0-2ef8-4b77-b1da-38a474572790

**Comment by pipeeeeees** [comment]
Hey congrats! I will add it to the repo. If you would like to add some to the list yourself at any point, you are more than welcome to fork, commit your changes, and pull request!
