### ISSUE TITLE
Homelander Waze Voice

### ISSUE THREAD

**Issue by Julchensid2303** [pipeeeeees/waze-voicepack-links#54]
I created this Waze voice pack using AI, as I wanted to have Homelander as a Waze voice. I named these callouts according to the guide and would be happy if you could create the voice for me. Thanks for helping to archive all these awesome voices for us :)
[Waze Homelander.zip](https://github.com/user-attachments/files/16324816/Waze.Homelander.zip)

**Comment by pipeeeeees** [comment]
Hey, try this: https://waze.com/ul?acvp=9e677a27-8421-41d7-9486-dce48fceca2c

**Comment by pipeeeeees** [comment]
Converted: Waze Homelander; Bitrate: 127k; Folder Size: 0.77 MB

was able to keep a very high bitrate with these files

**Comment by Julchensid2303** [comment]
Thank you so much. It’s working very nicely, have a pleasant day :)
