### ISSUE TITLE
J.A.R.V.I.S. AI generated

### ISSUE THREAD

**Issue by setokaibakg** [pipeeeeees/waze-voicepack-links#55]
Hello, Thanks so much in advance for doing this. I couldn't figure out for the life of me on how to upload the mp3 files to make a Waze pack, so thanks for taking the time to do this. I hope other people will enjoy this.
[J_wazze.zip](https://github.com/user-attachments/files/16366301/J_wazze.zip)

**Comment by pipeeeeees** [comment]
https://waze.com/ul?acvp=80500745-1d96-437c-bad7-f41fa07dab13 try this

**Comment by setokaibakg** [comment]
Looks good. Thanks so much.
