### ISSUE TITLE
GladOS Custom In-character responses (TTS Generated)

### ISSUE THREAD

**Issue by Sonictheyo19** [pipeeeeees/waze-voicepack-links#56]
Hey there, thanks in advance for this! I found the other GladOS voice listed didn't have the most in-character responses for stuff, so I took the opportunity to make a voicepack that felt a bit more true to her character. The voice was generated using this TTS tool https://www.nerdaxic.com/glados-voice-generator/ so I'm not sure if it would count as being AI generated or not. 

Attached is a folder with all the files in WAV format. If they need to be in MP3 format, just let me know and I can recompress them.

Have a great day, and thanks again! 

[GladOSWaze.zip](https://github.com/user-attachments/files/16503725/GladOSWaze.zip)

**Comment by pipeeeeees** [comment]
If you could put them into mp3, that would work best with my scripts

**Comment by Sonictheyo19** [comment]
Awesome, I'll shoot a converted folder once I have time after work.

**Comment by Sonictheyo19** [comment]
[GladosWazeSoundsMP3s.zip](https://github.com/user-attachments/files/16515928/GladosWazeSoundsMP3s.zip)
Here's the updated with the mp3 files instead, let me know if you'd need anything else! 😄

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=ea5e50fe-7d82-4421-b6ef-b7101755622c

**Comment by Sonictheyo19** [comment]
Just finished a drive with her and I can attest, it works perfectly! Thanks
so much! 😊

**Comment by Sonictheyo19** [comment]
Sorry just a quick question, would it be possible to update the tag on the list from Sonictheyo19 to D³Entertainment? I've been transitioning away from that old username and didn't catch that github was still that lol. not a huge deal if not

**Comment by pipeeeeees** [comment]
Done
