### ISSUE TITLE
British Female Voice - "Gemma"

### ISSUE THREAD

**Issue by Wilke1991** [pipeeeeees/waze-voicepack-links#59]
[Gemma Voice Files.zip](https://github.com/user-attachments/files/16735648/Gemma.Voice.Files.zip)

I intend to do metric only with Waze, so I skipped the vocals for the miles.  Thanks for the help with this.

**Comment by pipeeeeees** [comment]
Hey try this: https://waze.com/ul?acvp=24a2c89f-f38e-4fb1-bd71-9112acb4489e

Thank you for the generous donation, by the way. I appreciate your support!

**Comment by Wilke1991** [comment]
Just got back from an opportunity to live test the new voice pack, and it worked flawlessly.  The quality of the audio is excellent, and I'm very satisfied with the results.  Thank you for helping out with this one - it came out perfectly.

**Comment by pipeeeeees** [comment]
Anytime! If you find yourself wanting to make another, just open a new issue 🫡 happy driving
