### ISSUE TITLE
Hatsune Miku voice in french

### ISSUE THREAD

**Issue by Tijimu** [pipeeeeees/waze-voicepack-links#62]
Hi,
Is this possible to add this pack please ? It's Hatsune Miku voice but in french (not made with IA).
Thanks !
[Hatsune Miku FR.zip](https://github.com/user-attachments/files/16839387/Hatsune.Miku.FR.zip)

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=97eb5041-00f0-400b-ac26-c9ee283c7aa6

**Comment by Tijimu** [comment]
Perfect thanks !
