### ISSUE TITLE
question about creating a voice pack with personal private recordings

### ISSUE THREAD

**Issue by eelish669** [pipeeeeees/waze-voicepack-links#63]
Hi there :)
I have some recordings for waze of my varoius family members which i want to turn into a pack, but i'd like the recordings to be private as my family wouldnt want them to be accesible online.
Will you be willing to help me with such a pack or do you only create public packs?

**Comment by pipeeeeees** [comment]
> Hi there :) I have some recordings for waze of my varoius family members which i want to turn into a pack, but i'd like the recordings to be private as my family wouldnt want them to be accesible online. Will you be willing to help me with such a pack or do you only create public packs?

Yeah just DM the files on discord (@ pipeeeeees) and I can do it for you privately if you want to trust me with converting it. Or follow the tutorial poggermannen mentioned if you're tech savvy

**Comment by eelish669** [comment]
thank you!!!!!
I followed the tutorial but for some reason the waze did not get updated.
Sending you the files on discord now

**Comment by pipeeeeees** [comment]
closed over discord
