### ISSUE TITLE
New Voicepack former president Obama

### ISSUE THREAD

**Issue by Edwin-VC** [pipeeeeees/waze-voicepack-links#64]
Hi David. 

Cool project with the Waze Voicepacks. I think one Voicepack should be added: former president Barack Obama.

Of course this is generated by TTS/AI. I am using a paid subscription with Lazybird. They don't seem to support the typical 'uhm' phrasing, but then again we only have a couple of second for each message... 😉

Rest assured, no political statements or foul language. Maybe just a bit of fun appropriate for Barack Obama where possible.

Hopefully you can help me create the Voicepack and make it available to others as well.

Let me know if there is anything else I can do.

With kind regards,
Edwin Valenti Clari (now residing in The Netherlands but used to live in Austell, GA as well. Love ATL!)

[Waze Voicepack  - Obama - pipeeeeees - Submit.zip](https://github.com/user-attachments/files/16978682/Waze.Voicepack.-.Obama.-.pipeeeeees.-.Submit.zip)

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=b56ef1b1-85ab-4c12-96cd-7713fed9269e

**Comment by pipeeeeees** [comment]
Happy to help make voicepacks! Especially for a fellow Georgian. Things are finally cooling down around Atlanta. Looking more and more like fall around here with each passing week. May not compare to the netherlands in many ways, but Atlanta will always feel like home to me.

You take the man out of the city, not the city out the man!
