### ISSUE TITLE
MasterChief in French

### ISSUE THREAD

**Issue by jacoch** [pipeeeeees/waze-voicepack-links#66]
Hi David,

Someone in a French Facebook group (https://www.facebook.com/groups/wazefrance/) posted all the files of the official MasterChief voice in French, that is unfortunately not available in Waze anymore. Is it possible to create a pack with these files? You can download them here : https://www.dropbox.com/scl/fi/opop371j7gi3sj3e69xhu/MC-French.rar?rlkey=oosqjdsput86q7ui4vw1ck6uq&dl=1.

Thanks in advance

**Comment by pipeeeeees** [comment]
Try: https://waze.com/ul?acvp=0922151d-1538-4596-bf53-ddc21a6f0175

**Comment by jacoch** [comment]
Hi. Works great. Thanks for the help.
