### ISSUE TITLE
MasterChief_SpanishIA

### ISSUE THREAD

**Issue by juanin-ship-it** [pipeeeeees/waze-voicepack-links#67]
Hello there!
I made a custom voice using some recordings from TikTok, YouTube, and Facebook videos. I know not all the voice lines were available, but I tried to get as many as I could. For the ones I couldn't find, I used Cortana's AI voice. Two voice lines are left in English (sorry, I like them that way).
[JefeMaestro0p0.zip](https://github.com/user-attachments/files/17038412/JefeMaestro0p0.zip)
Thanks in advance for the support! I tried to do it myself, but it was a complete failure.

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=ffe55ef3-083d-4c6d-aaca-779484b173dc

**Comment by juanin-ship-it** [comment]
This totally worked, tysm
