### ISSUE TITLE
Add new Voice Pack 'Sylus Ai'

### ISSUE THREAD

**Issue by ArvyMinsk** [pipeeeeees/waze-voicepack-links#68]
Hi!
I made an AI generated Voice pack for Sylus from Love and Deepspace, is it possible to add it to the list?
I'd really love to drive with him as my navigating voice.
I hope all the files are fine!
I love using your guys voice packs! 

Thank you! :)

Best wishes
Lisa
[SylusLnDAI.zip](https://github.com/user-attachments/files/17270513/SylusLnDAI.zip)

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=16c19f73-dfa4-4402-bfd4-c03b603fba63

**Comment by pipeeeeees** [comment]
see latest commit

**Comment by ArvyMinsk** [comment]
Thank you!!!
