### ISSUE TITLE
Can you please create a pack using these sounds?

### ISSUE THREAD

**Issue by alexmorak** [pipeeeeees/waze-voicepack-links#70]
It's in Greek language which I think lacks in voices. Thank you.

[Daniel_Greek.zip](https://github.com/user-attachments/files/17342990/Daniel_Greek.zip)
[Kyriakos_Greek.zip](https://github.com/user-attachments/files/17343010/Kyriakos_Greek.zip)

**Comment by pipeeeeees** [comment]
Try this for Daniel: https://waze.com/ul?acvp=9738b347-b15d-4b40-ab67-d1c574406ae7
and this for Kyriakos: https://waze.com/ul?acvp=c8830c28-39ad-4bf6-be76-dfad40fbad1a

**Comment by alexmorak** [comment]
Thank you.
In Daniel pack the Crash Reported has some romanian voice.

**Comment by pipeeeeees** [comment]
Noted. That was what was provided in your link. If this was in error, send me the corrected file or zip and I can give you another

**Comment by alexmorak** [comment]
That was my mistake sorry. It's OK.
