### ISSUE TITLE
Can you please create a pack using these files?

### ISSUE THREAD

**Issue by auntoy69** [pipeeeeees/waze-voicepack-links#71]
The voice is DJ Cara from Grand Theft Auto V (AI Generated). 
[DJ Cara From GTA V (AI Generated).zip](https://github.com/user-attachments/files/17350605/DJ.Cara.From.GTA.V.AI.Generated.zip)

I only had enough credits to generate most of the voices so please replace the missing ones with default voices from Waze.
Also it is in Meters only. I will try and generate more if needed later.

My discord username is auntoy

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=5624b460-3833-473e-8e8d-304a943b34c8

**Comment by pipeeeeees** [comment]
This sounds so similar to the real GTA 5 DJ Cara. I think personally people would love it if you made the rest of the StartDrives and added imperial units

Been meaning to have someone do the Forza Horizon 5 gps voice for the longest time. That would be sick

**Comment by pipeeeeees** [comment]
Not to mention whenever GTA 6 comes out, making a voicepack with that new GPS voice would be killer. Just thinking out loud here

**Comment by auntoy69** [comment]
Thanks for the reply. I have added the missing voices. 
Here is the new zip file. 
[DJ Cara AI voice by auntoy.zip](https://github.com/user-attachments/files/17364784/DJ.Cara.AI.voice.by.auntoy.zip)
Also note that I have named the rerouting voice to 'Rerouting.mp3'. Idk if this is correct.

About the Forza Horizon 5 gps voice, I was also wishing for it for a long time. I might do it in the future. :)

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=dca587f2-7e3a-4dfd-aeaa-4bad04b390dc

**Comment by auntoy69** [comment]
> Try this: https://waze.com/ul?acvp=dca587f2-7e3a-4dfd-aeaa-4bad04b390dc
I tried it but the starting voice is still a male voice somehow.

**Comment by pipeeeeees** [comment]
The files up on the server are correct (https://voice-prompts-ipv6.waze.com/dca587f2-7e3a-4dfd-aeaa-4bad04b390dc.tar.gz), so this must be a client-side issue

now I believe this bug where the start drive voice is told in the default voice but all others play fine is a bug that has existed for a number of months now judging from what ive seen on r/waze. I don't use waze at all really surprisingly so I have not been keeping up on if they will fix the app. I think it affects iOS and android?
