### ISSUE TITLE
Cars Flash McQueen FR booost

### ISSUE THREAD

**Issue by 63manu78** [pipeeeeees/waze-voicepack-links#72]
Hi,
Could you create a Voice pack with this files with maximum amplification without saturation please ?
Regards
[Cars voices pack.zip](https://github.com/user-attachments/files/17355311/Cars.voices.pack.zip)

**Comment by pipeeeeees** [comment]
Your zip file is empty. Please send another one. 

I can amplify the mp3 files to an ear-drum exploding extent... but unsure at what point saturation is achieved. If you know how I can verify that in python, let me know. Otherwise I will just send you like 5 different levels of amplified audio for you to try out

**Comment by 63manu78** [comment]
Here the zip again
[Cars voices pack.zip](https://github.com/user-attachments/files/17360763/Cars.voices.pack.zip)
It's OK ?

**Comment by pipeeeeees** [comment]
7dB increase: https://waze.com/ul?acvp=5e87b992-c5da-42d4-9773-c693d1b0537b
10dB increase: https://waze.com/ul?acvp=81ca4744-7072-48a8-835f-b6e31b65b950
14dB increase: https://waze.com/ul?acvp=57d60311-e370-419b-a957-9e3913453647
17dB increase: https://waze.com/ul?acvp=3113d1a2-ea30-4cfd-90b4-47e2683925b3
20dB increase: https://waze.com/ul?acvp=910bc205-36a3-4203-8833-dc7e956f5b59

**Comment by 63manu78** [comment]
Hi, thanks for that.
I'm going to try on Android Auto but only the 7dB and 10dB versions because above that, you can hear the saturation and it's not very audible.
After a few tries, I'll tell you which one I keep.
Thanks again

**Comment by 63manu78** [comment]
Good morning,
So I tested the different variants and I will keep the 7db.
I just have one last request: I seem to be missing the Rerouting sound (see capture).
![Screenshot_20241104-230752](https://github.com/user-attachments/assets/e8cb6afc-bfd2-4392-a0b9-8bb3c2d1d4a3)

Can you redo a pack for me including the attached mp3 file for the Rerouting sound please?
[TickerPoints.zip](https://github.com/user-attachments/files/17624557/TickerPoints.zip)

Thank you so much

**Comment by pipeeeeees** [comment]
here is 7 dB with tickerpoints added in (although without tickerpoints, it defaults to the exact same sound I think... not sure about that

try this: https://waze.com/ul?acvp=42f3c028-b6b0-426a-b283-c8f21af9797a

**Comment by 63manu78** [comment]
Hi,
Looks good to me, thank you very much.
As indicated previously, I will keep the +7db version so I will let you decide whether or not you delete the other versions from Waze hosting.
Thanks again for the work
