### ISSUE TITLE
Afroditi Greek Voice

### ISSUE THREAD

**Issue by alexmorak** [pipeeeeees/waze-voicepack-links#74]
Can you please make a pack with these sounds? Thank you.

[Afroditi_Greek.zip](https://github.com/user-attachments/files/17360599/Afroditi_Greek.zip)

**Comment by pipeeeeees** [comment]
Trythis: https://waze.com/ul?acvp=095cd118-ee81-4b63-8121-0bfc757f9c0b

**Comment by alexmorak** [comment]
Everything worked fine. You can add it in the homepage for other greek users too if you want!
