### ISSUE TITLE
Professional italian HD voice pack with funny start drives

### ISSUE THREAD

**Issue by Sberla996** [pipeeeeees/waze-voicepack-links#75]
Hello, I've created this HD voice pack with a female voice in Italian using Google text-to-speech AI.
The default Italian voice is horrible so I created this new one, everything is in a professional tone except for the start drives, thank you for uploading it!
[Voce italiana professionale con partenze divertenti.zip](https://github.com/user-attachments/files/17409517/Voce.italiana.professionale.con.partenze.divertenti.zip)

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=5b992867-ee8d-4fad-9279-c5f236da041f
