### ISSUE TITLE
[AI] Hololive A-Chan character voice over

### ISSUE THREAD

**Issue by accreroll** [pipeeeeees/waze-voicepack-links#77]
Hello, could you make this a Waze voice pack for me? Thanks. 
[A chan.zip](https://github.com/user-attachments/files/17585560/A.chan.zip)

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=eb3aa874-4bfa-4663-abc8-eb188442b2c2

had to convert them down to 36k bitrate so audio may not be as good, but it's the best audio quality possible given the limitations

**Comment by accreroll** [comment]
Thank you so much. 

Allg, I had to batch convert from a WAV to mp3 lol. This is great work.
