### ISSUE TITLE
Voice missing

### ISSUE THREAD

**Issue by taldei** [pipeeeeees/waze-voicepack-links#8]
Hi! Until some months ago, there was the voice of Maisie and Blue from the movie "The Sea Beast"
https://blog.google/waze/go-on-an-epic-adventure-with-netflixs-the-sea-beast/
Can you find it?
Thanks for creating this page!

**Comment by pipeeeeees** [comment]
Hey! No problem, I will attempt to find and generate a link next week when I return from vacation. Feel free to add more requests in the meantime!

**Comment by pipeeeeees** [comment]
See the most recent commit for 'The Sea Beast' voicepack - enjoy!

**Comment by taldei** [comment]
Thank you!
