### ISSUE TITLE
MasterChief_SpanishIA v0.2

### ISSUE THREAD

**Issue by juan117xz** [pipeeeeees/waze-voicepack-links#81]
This update includes:

Volume Normalization: The audio files from the previous pack have been processed to ensure consistent volume levels across all samples.
Voice Replacement: Some of the original Cortana phrases have been replaced with AI Master Chief voice lines for a better thematic alignment.
Thanks in advance for the support! I tried to do it myself, but it was a complete failure.

[JefeMaestro0.2.zip](https://github.com/user-attachments/files/17706318/JefeMaestro0.2.zip)

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=93cbdcb4-32d8-4601-81df-085dff398eac

**Comment by juan117xz** [comment]
Thank you for your contribution! The implementation works smoothly, and I appreciate your effort. I noticed Waze will not support uploading .mp3 files for custom voices as a built-in feature (sad)
It would be nice to have a video tutorial of the process you make.

**Comment by pipeeeeees** [comment]
Noted - I've thought about making a tutorial video. If I end up making one, I will post it onto the readme
