### ISSUE TITLE
NOD EVA Command And Conquer 3

### ISSUE THREAD

**Issue by MeanSoldier** [pipeeeeees/waze-voicepack-links#82]
Hope you like it and add it to your list

https://drive.google.com/drive/folders/1cj4WTg4OhSMe2uh_QQGkhB-wTgAJHOOq?usp=sharing

**Comment by pipeeeeees** [comment]
Renamed  "Complete.mp3" to "Arrive.mp3" and "Sixt.mp3" to "Sixth.mp3" as I believe those are were the intended filenames

Try this: https://waze.com/ul?acvp=2747acc6-983f-4989-864e-fd3a4d140ee8

**Comment by MeanSoldier** [comment]
Seems fine, I noticed you cut some of the files and the distances are missing :)

**Comment by pipeeeeees** [comment]
Cool cool. Let me know if you want any changes. Out of curiosity, which files were cut? Which distances are missing? The only changes I made were to `Complete.mp3` and `Sixt.mp3` - otherwise, the files should be untouched other than maybe some bitrate adjustment
