### ISSUE TITLE
[AI] Major & Konon Voice Pack

### ISSUE THREAD

**Issue by szpuntoo** [pipeeeeees/waze-voicepack-links#83]
Polish voice pack, funny sounds in national language with Major and Konon.

https://drive.google.com/file/d/1KYP71B4R23HrREmjH2m9UgR4GSiF1Rn7/view?usp=drive_link

Please add :)))

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=05f695e6-f538-44aa-a71a-af9cfe705b31

**Comment by szpuntoo** [comment]
Thank you bro! When i started Waze with this sound pack, my reaction is OMG ! It's Perfectly in 99%, but missing one sound. Link bellow
https://drive.google.com/file/d/15D9WghTWM-YqjUu-sSphcjONXwjFOJL5/view?usp=drive_link

**Comment by pipeeeeees** [comment]
Try this: https://waze.com/ul?acvp=cccbebb1-81aa-46de-bb86-1d28c08899aa

**Comment by szpuntoo** [comment]
Perfect 👌
