### ISSUE TITLE
Auronplay_twitch Era

### ISSUE THREAD

**Issue by l4t0r** [pipeeeeees/waze-voicepack-links#9]
Hello, I have created the Auronplay custom voice pack from the Twitch era. I've used fakeyou AI, I know it's not the best way to create a custom voice, but I've worked on this one with that AI, and then processed it with reaper to improve the sound picks. I have the voice file pack for almost all the sounds, it includes miles and kilometers, but I have not been able to import it in waze, my device is rooted so I can access the directories without problem, I have been guided by a voice pack imported already existing, could you help me?

**Comment by pipeeeeees** [comment]
Shoot me a message on discord @pipeeeeees and I’ll see how I can help
